metadata:
  name: nw-example-api01
  namespace: dev
spec:
  replicas: 1
  image: nginx
  containerPort: 80
configuration:
  - name: "PRUEBA_CONFIG"
    configMapName: nginx-config
    valueKey: prueba
  - name: "PRUEBA2_CONFIG"
    configMapName: nginx-config
    valueKey: prueba2