metadata:
  name: nw-example-api01
spec:
  replicas: 1
  image: nginx
  containerPort: 80
  configuration:
    key: PRUEBA_CONFIG
      configMapName: nginx-config
      valueKey: prueba
    key: PRUEBA2_CONFIG
      configMapName: nginx-config
      valueKey: prueba2