apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nubi-4
spec:
  selector:
    matchLabels:
      run: demo-nubi-4
  replicas: 1
  template:
    metadata:
      labels:
        run: demo-nubi-4
    spec:
      containers:
      - name: demo-nubi-4
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nubi-4
  labels:
    run: demo-nubi-4
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    run: demo-nubi-4
