{{- range $configPath, $configBytes := .Files.Glob "config/*.yml" -}}
{{ $configData := $.Files.Get $configPath | fromYaml -}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configData.metadata.name }}
  namespace: {{ $configData.metadata.namespace }}
  labels:
    run: {{ $configData.metadata.name }}
data:
  {{- range $key, $val := $configData.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

{{ end -}}
