{{- range $appsPath, $appsBytes := .Files.Glob "apps/*.yml" -}}
{{ $appsData := $.Files.Get $appsPath | fromYaml -}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appsData.metadata.name }}
spec:
  selector:
    matchLabels:
      run: {{ $appsData.metadata.name }}
  replicas: {{ $appsData.spec.replicas }}
  template:
    metadata:
      labels:
        run: {{ $appsData.metadata.name }}
      annotations:
        checksum/config: {{ include (printf "config/$s.yml" $appsData.metadata.name ) . | sha256sum }}
    spec:
      containers:
      - name: {{ $appsData.metadata.name }}
        image: {{ $appsData.spec.image }}
        ports:
        - containerPort: {{ $appsData.spec.containerPort }}
        env:
        {{- range $appsData.spec.configuration }}
        - name: {{ .key }}
          valueFrom:
            configMapKeyRef:
              name: {{ .configMapName }}
              key: {{ .valueKey }}
        {{- end }}

{{ end -}}