{{- range $originsPath, $globlBytes := .Files.Glob "apps/*.yml" -}}
{{ $originsData := $.Files.Get $originsPath | fromYaml -}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $originsData.metadata.name }}
spec:
  selector:
    matchLabels:
      run: {{ $originsData.metadata.name }}
  replicas: {{ $apporiginsDataData.spec.replicas }}
  template:
    metadata:
      labels:
        run: {{ $originsData.metadata.name }}
      annotations:
        checksum/config: {{ include (printf "config/$s.yml" $originsData.metadata.name ) . | sha256sum }}
    spec:
      containers:
      - name: {{ $originsData.metadata.name }}
        image: {{ $originsData.spec.image }}
        ports:
        - containerPort: {{ $originsData.spec.containerPort }}

{{ end -}}