{{- range $deployPath, $deployBytes := .Files.Glob "apps/*.yml" -}}
{{ $deployData := $.Files.Get $deployPath | fromYaml -}}

---

apiVersion: v1
kind: Deployment
metadata:
  name: {{ $deployData.metadata.name }}
  namespace: {{ $deployData.metadata.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ $deployData.metadata.name }}
  replicas: {{ $deployData.spec.replicas }}
  template:
    metadata:
      labels:
        run: {{ $deployData.metadata.name }}
      annotations:
        checksum/config: {{ $.Files.Get (print "config/" $deployData.metadata.name ".yml") | sha256sum  }}
    spec:
      containers:
      - name: {{ $deployData.metadata.name }}
        image: {{ $deployData.spec.image }}
        ports:
        - containerPort: {{ $deployData.spec.containerPort }}
        env:
        {{- range $deployData.configuration }}
        - name: {{ .name }}
          valueFrom:
            configMapKeyRef:
              name: {{ .configMapName }}
              key: {{ .valueKey }}
        {{- end }}
{{ end -}}