{{- range $servicePath, $serviceBytes := .Files.Glob "svc/*.yml" -}}
{{ $serviceData := $.Files.Get $servicePath | fromYaml -}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceData.metadata.name }}
  labels:
    run: {{ $serviceData.metadata.name }}
spec:
  ports:
  - port: {{ $serviceData.spec.port }}
    protocol: TCP
  type: {{ $serviceData.spec.type }}
  selector:
    run: {{ $serviceData.metadata.name }}

{{ end -}}
