apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deploys
    checksum/config: {{ include (print $.Template.BasePath "/app1/configmap.yaml") . | sha256sum }}
  name: app1-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.app1.spec.destination.namespace }}
    server: {{ .Values.app1.spec.destination.server }}
  project: dev
  source:
    path: {{ .Values.app1.spec.source.path }}
    repoURL: {{ .Values.app1.spec.source.repoURL }}
    targetRevision: {{ .Values.app1.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
